{% set name = "opentelemetry-instrumentation-celery" %}
{% set version = "0.38b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_celery-{{ version }}.tar.gz
  sha256: ef0c7d64865dd67615ee6f2f2f81cc127de1649c05dcc18e6d64496183739a4c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.38b0
    - opentelemetry-semantic-conventions ==0.38b0
    # - pytest 
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-celery 
    # - importlib-metadata ==4.13.0
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-celery
  summary: OpenTelemetry Celery Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
